[project]
name = 'Decentralized-Insurance-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.policy-management]
path = 'contracts/policy-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.risk-pool]
path = 'contracts/risk-pool.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
